CREATE TABLE Users (
	ID SERIAL PRIMARY KEY,
	Login VARCHAR(255),
	Password VARCHAR(255),
	BirthDt TIMESTAMP CHECK (BirthDt < now()),
	JoinYear VARCHAR(4),
	ClassName VARCHAR(100),
	Pro BOOLEAN
);

CREATE TABLE Subjects (
	ID SERIAL PRIMARY KEY,
	Name VARCHAR(255)
);

CREATE TABLE HomeWorks (
	ID SERIAL PRIMARY KEY,
	UserID INTEGER REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	SubjectID INTEGER REFERENCES Subjects(ID),
	Description VARCHAR(255),
	AddDate TIMESTAMP,
	EndDate TIMESTAMP
);

CREATE TABLE HomeWorks (
	ID SERIAL PRIMARY KEY,
	UserID INTEGER REFERENCES Users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	SubjectID INTEGER REFERENCES Subjects(ID),
	Description VARCHAR(255),
	AddDate TIMESTAMP,
	EndDate TIMESTAMP
);